<?php
/**
 * ExecutionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ExecutionResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ExecutionResponse
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExecutionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExecutionResponse"
     */
    public function testExecutionResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "parent_url"
     */
    public function testPropertyParentUrl()
    {
    }

    /**
     * Test attribute "super_execution_id"
     */
    public function testPropertySuperExecutionId()
    {
    }

    /**
     * Test attribute "super_execution_url"
     */
    public function testPropertySuperExecutionUrl()
    {
    }

    /**
     * Test attribute "process_instance_id"
     */
    public function testPropertyProcessInstanceId()
    {
    }

    /**
     * Test attribute "process_instance_url"
     */
    public function testPropertyProcessInstanceUrl()
    {
    }

    /**
     * Test attribute "suspended"
     */
    public function testPropertySuspended()
    {
    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
    }
}
