<?php
/**
 * JobResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * JobResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description JobResponse
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JobResponse"
     */
    public function testJobResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "process_instance_id"
     */
    public function testPropertyProcessInstanceId()
    {
    }

    /**
     * Test attribute "process_instance_url"
     */
    public function testPropertyProcessInstanceUrl()
    {
    }

    /**
     * Test attribute "process_definition_id"
     */
    public function testPropertyProcessDefinitionId()
    {
    }

    /**
     * Test attribute "process_definition_url"
     */
    public function testPropertyProcessDefinitionUrl()
    {
    }

    /**
     * Test attribute "execution_id"
     */
    public function testPropertyExecutionId()
    {
    }

    /**
     * Test attribute "execution_url"
     */
    public function testPropertyExecutionUrl()
    {
    }

    /**
     * Test attribute "retries"
     */
    public function testPropertyRetries()
    {
    }

    /**
     * Test attribute "exception_message"
     */
    public function testPropertyExceptionMessage()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
    }
}
