<?php
/**
 * TaskQueryRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TaskQueryRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description TaskQueryRequest
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskQueryRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TaskQueryRequest"
     */
    public function testTaskQueryRequest()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "sort"
     */
    public function testPropertySort()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "name_like"
     */
    public function testPropertyNameLike()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "description_like"
     */
    public function testPropertyDescriptionLike()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "minimum_priority"
     */
    public function testPropertyMinimumPriority()
    {
    }

    /**
     * Test attribute "maximum_priority"
     */
    public function testPropertyMaximumPriority()
    {
    }

    /**
     * Test attribute "assignee"
     */
    public function testPropertyAssignee()
    {
    }

    /**
     * Test attribute "assignee_like"
     */
    public function testPropertyAssigneeLike()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "owner_like"
     */
    public function testPropertyOwnerLike()
    {
    }

    /**
     * Test attribute "unassigned"
     */
    public function testPropertyUnassigned()
    {
    }

    /**
     * Test attribute "delegation_state"
     */
    public function testPropertyDelegationState()
    {
    }

    /**
     * Test attribute "candidate_user"
     */
    public function testPropertyCandidateUser()
    {
    }

    /**
     * Test attribute "candidate_group"
     */
    public function testPropertyCandidateGroup()
    {
    }

    /**
     * Test attribute "candidate_group_in"
     */
    public function testPropertyCandidateGroupIn()
    {
    }

    /**
     * Test attribute "involved_user"
     */
    public function testPropertyInvolvedUser()
    {
    }

    /**
     * Test attribute "process_instance_id"
     */
    public function testPropertyProcessInstanceId()
    {
    }

    /**
     * Test attribute "process_instance_business_key"
     */
    public function testPropertyProcessInstanceBusinessKey()
    {
    }

    /**
     * Test attribute "process_instance_business_key_like"
     */
    public function testPropertyProcessInstanceBusinessKeyLike()
    {
    }

    /**
     * Test attribute "process_instance_id_in"
     */
    public function testPropertyProcessInstanceIdIn()
    {
    }

    /**
     * Test attribute "process_definition_id"
     */
    public function testPropertyProcessDefinitionId()
    {
    }

    /**
     * Test attribute "process_definition_key"
     */
    public function testPropertyProcessDefinitionKey()
    {
    }

    /**
     * Test attribute "process_definition_name"
     */
    public function testPropertyProcessDefinitionName()
    {
    }

    /**
     * Test attribute "process_definition_key_like"
     */
    public function testPropertyProcessDefinitionKeyLike()
    {
    }

    /**
     * Test attribute "process_definition_name_like"
     */
    public function testPropertyProcessDefinitionNameLike()
    {
    }

    /**
     * Test attribute "execution_id"
     */
    public function testPropertyExecutionId()
    {
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "created_before"
     */
    public function testPropertyCreatedBefore()
    {
    }

    /**
     * Test attribute "created_after"
     */
    public function testPropertyCreatedAfter()
    {
    }

    /**
     * Test attribute "exclude_sub_tasks"
     */
    public function testPropertyExcludeSubTasks()
    {
    }

    /**
     * Test attribute "task_definition_key"
     */
    public function testPropertyTaskDefinitionKey()
    {
    }

    /**
     * Test attribute "task_definition_key_like"
     */
    public function testPropertyTaskDefinitionKeyLike()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "due_before"
     */
    public function testPropertyDueBefore()
    {
    }

    /**
     * Test attribute "due_after"
     */
    public function testPropertyDueAfter()
    {
    }

    /**
     * Test attribute "without_due_date"
     */
    public function testPropertyWithoutDueDate()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "include_task_local_variables"
     */
    public function testPropertyIncludeTaskLocalVariables()
    {
    }

    /**
     * Test attribute "include_process_variables"
     */
    public function testPropertyIncludeProcessVariables()
    {
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
    }

    /**
     * Test attribute "tenant_id_like"
     */
    public function testPropertyTenantIdLike()
    {
    }

    /**
     * Test attribute "without_tenant_id"
     */
    public function testPropertyWithoutTenantId()
    {
    }

    /**
     * Test attribute "candidate_or_assigned"
     */
    public function testPropertyCandidateOrAssigned()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "task_variables"
     */
    public function testPropertyTaskVariables()
    {
    }

    /**
     * Test attribute "process_instance_variables"
     */
    public function testPropertyProcessInstanceVariables()
    {
    }
}
