<?php
/**
 * TaskRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TaskRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description TaskRequest
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TaskRequest"
     */
    public function testTaskRequest()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "assignee"
     */
    public function testPropertyAssignee()
    {
    }

    /**
     * Test attribute "delegation_state"
     */
    public function testPropertyDelegationState()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "parent_task_id"
     */
    public function testPropertyParentTaskId()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "tenant_id"
     */
    public function testPropertyTenantId()
    {
    }

    /**
     * Test attribute "form_key"
     */
    public function testPropertyFormKey()
    {
    }

    /**
     * Test attribute "owner_set"
     */
    public function testPropertyOwnerSet()
    {
    }

    /**
     * Test attribute "assignee_set"
     */
    public function testPropertyAssigneeSet()
    {
    }

    /**
     * Test attribute "delegation_state_set"
     */
    public function testPropertyDelegationStateSet()
    {
    }

    /**
     * Test attribute "name_set"
     */
    public function testPropertyNameSet()
    {
    }

    /**
     * Test attribute "description_set"
     */
    public function testPropertyDescriptionSet()
    {
    }

    /**
     * Test attribute "duedate_set"
     */
    public function testPropertyDuedateSet()
    {
    }

    /**
     * Test attribute "priority_set"
     */
    public function testPropertyPrioritySet()
    {
    }

    /**
     * Test attribute "parent_task_id_set"
     */
    public function testPropertyParentTaskIdSet()
    {
    }

    /**
     * Test attribute "category_set"
     */
    public function testPropertyCategorySet()
    {
    }

    /**
     * Test attribute "tenant_id_set"
     */
    public function testPropertyTenantIdSet()
    {
    }

    /**
     * Test attribute "form_key_set"
     */
    public function testPropertyFormKeySet()
    {
    }
}
