<?php
/**
 * FormDataResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FormDataResponse Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormDataResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FormDataResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'form_key' => 'string',
        'deployment_id' => 'string',
        'process_definition_id' => 'string',
        'process_definition_url' => 'string',
        'task_id' => 'string',
        'task_url' => 'string',
        'form_properties' => '\Swagger\Client\Model\RestFormProperty[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'form_key' => null,
        'deployment_id' => null,
        'process_definition_id' => null,
        'process_definition_url' => null,
        'task_id' => null,
        'task_url' => null,
        'form_properties' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'form_key' => 'formKey',
        'deployment_id' => 'deploymentId',
        'process_definition_id' => 'processDefinitionId',
        'process_definition_url' => 'processDefinitionUrl',
        'task_id' => 'taskId',
        'task_url' => 'taskUrl',
        'form_properties' => 'formProperties'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'form_key' => 'setFormKey',
        'deployment_id' => 'setDeploymentId',
        'process_definition_id' => 'setProcessDefinitionId',
        'process_definition_url' => 'setProcessDefinitionUrl',
        'task_id' => 'setTaskId',
        'task_url' => 'setTaskUrl',
        'form_properties' => 'setFormProperties'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'form_key' => 'getFormKey',
        'deployment_id' => 'getDeploymentId',
        'process_definition_id' => 'getProcessDefinitionId',
        'process_definition_url' => 'getProcessDefinitionUrl',
        'task_id' => 'getTaskId',
        'task_url' => 'getTaskUrl',
        'form_properties' => 'getFormProperties'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['form_key'] = isset($data['form_key']) ? $data['form_key'] : null;
        $this->container['deployment_id'] = isset($data['deployment_id']) ? $data['deployment_id'] : null;
        $this->container['process_definition_id'] = isset($data['process_definition_id']) ? $data['process_definition_id'] : null;
        $this->container['process_definition_url'] = isset($data['process_definition_url']) ? $data['process_definition_url'] : null;
        $this->container['task_id'] = isset($data['task_id']) ? $data['task_id'] : null;
        $this->container['task_url'] = isset($data['task_url']) ? $data['task_url'] : null;
        $this->container['form_properties'] = isset($data['form_properties']) ? $data['form_properties'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets form_key
     *
     * @return string
     */
    public function getFormKey()
    {
        return $this->container['form_key'];
    }

    /**
     * Sets form_key
     *
     * @param string $form_key form_key
     *
     * @return $this
     */
    public function setFormKey($form_key)
    {
        $this->container['form_key'] = $form_key;

        return $this;
    }

    /**
     * Gets deployment_id
     *
     * @return string
     */
    public function getDeploymentId()
    {
        return $this->container['deployment_id'];
    }

    /**
     * Sets deployment_id
     *
     * @param string $deployment_id deployment_id
     *
     * @return $this
     */
    public function setDeploymentId($deployment_id)
    {
        $this->container['deployment_id'] = $deployment_id;

        return $this;
    }

    /**
     * Gets process_definition_id
     *
     * @return string
     */
    public function getProcessDefinitionId()
    {
        return $this->container['process_definition_id'];
    }

    /**
     * Sets process_definition_id
     *
     * @param string $process_definition_id process_definition_id
     *
     * @return $this
     */
    public function setProcessDefinitionId($process_definition_id)
    {
        $this->container['process_definition_id'] = $process_definition_id;

        return $this;
    }

    /**
     * Gets process_definition_url
     *
     * @return string
     */
    public function getProcessDefinitionUrl()
    {
        return $this->container['process_definition_url'];
    }

    /**
     * Sets process_definition_url
     *
     * @param string $process_definition_url process_definition_url
     *
     * @return $this
     */
    public function setProcessDefinitionUrl($process_definition_url)
    {
        $this->container['process_definition_url'] = $process_definition_url;

        return $this;
    }

    /**
     * Gets task_id
     *
     * @return string
     */
    public function getTaskId()
    {
        return $this->container['task_id'];
    }

    /**
     * Sets task_id
     *
     * @param string $task_id task_id
     *
     * @return $this
     */
    public function setTaskId($task_id)
    {
        $this->container['task_id'] = $task_id;

        return $this;
    }

    /**
     * Gets task_url
     *
     * @return string
     */
    public function getTaskUrl()
    {
        return $this->container['task_url'];
    }

    /**
     * Sets task_url
     *
     * @param string $task_url task_url
     *
     * @return $this
     */
    public function setTaskUrl($task_url)
    {
        $this->container['task_url'] = $task_url;

        return $this;
    }

    /**
     * Gets form_properties
     *
     * @return \Swagger\Client\Model\RestFormProperty[]
     */
    public function getFormProperties()
    {
        return $this->container['form_properties'];
    }

    /**
     * Sets form_properties
     *
     * @param \Swagger\Client\Model\RestFormProperty[] $form_properties form_properties
     *
     * @return $this
     */
    public function setFormProperties($form_properties)
    {
        $this->container['form_properties'] = $form_properties;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

