<?php
/**
 * ProcessDefinitionResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ProcessDefinitionResponse Class Doc Comment
 *
 * @category Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProcessDefinitionResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProcessDefinitionResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'url' => 'string',
        'key' => 'string',
        'version' => 'int',
        'name' => 'string',
        'description' => 'string',
        'tenant_id' => 'string',
        'deployment_id' => 'string',
        'deployment_url' => 'string',
        'resource' => 'string',
        'diagram_resource' => 'string',
        'category' => 'string',
        'graphical_notation_defined' => 'bool',
        'suspended' => 'bool',
        'start_form_defined' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'url' => null,
        'key' => null,
        'version' => 'int32',
        'name' => null,
        'description' => null,
        'tenant_id' => null,
        'deployment_id' => null,
        'deployment_url' => null,
        'resource' => null,
        'diagram_resource' => null,
        'category' => null,
        'graphical_notation_defined' => null,
        'suspended' => null,
        'start_form_defined' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'url' => 'url',
        'key' => 'key',
        'version' => 'version',
        'name' => 'name',
        'description' => 'description',
        'tenant_id' => 'tenantId',
        'deployment_id' => 'deploymentId',
        'deployment_url' => 'deploymentUrl',
        'resource' => 'resource',
        'diagram_resource' => 'diagramResource',
        'category' => 'category',
        'graphical_notation_defined' => 'graphicalNotationDefined',
        'suspended' => 'suspended',
        'start_form_defined' => 'startFormDefined'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'url' => 'setUrl',
        'key' => 'setKey',
        'version' => 'setVersion',
        'name' => 'setName',
        'description' => 'setDescription',
        'tenant_id' => 'setTenantId',
        'deployment_id' => 'setDeploymentId',
        'deployment_url' => 'setDeploymentUrl',
        'resource' => 'setResource',
        'diagram_resource' => 'setDiagramResource',
        'category' => 'setCategory',
        'graphical_notation_defined' => 'setGraphicalNotationDefined',
        'suspended' => 'setSuspended',
        'start_form_defined' => 'setStartFormDefined'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'url' => 'getUrl',
        'key' => 'getKey',
        'version' => 'getVersion',
        'name' => 'getName',
        'description' => 'getDescription',
        'tenant_id' => 'getTenantId',
        'deployment_id' => 'getDeploymentId',
        'deployment_url' => 'getDeploymentUrl',
        'resource' => 'getResource',
        'diagram_resource' => 'getDiagramResource',
        'category' => 'getCategory',
        'graphical_notation_defined' => 'getGraphicalNotationDefined',
        'suspended' => 'getSuspended',
        'start_form_defined' => 'getStartFormDefined'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['key'] = isset($data['key']) ? $data['key'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['tenant_id'] = isset($data['tenant_id']) ? $data['tenant_id'] : null;
        $this->container['deployment_id'] = isset($data['deployment_id']) ? $data['deployment_id'] : null;
        $this->container['deployment_url'] = isset($data['deployment_url']) ? $data['deployment_url'] : null;
        $this->container['resource'] = isset($data['resource']) ? $data['resource'] : null;
        $this->container['diagram_resource'] = isset($data['diagram_resource']) ? $data['diagram_resource'] : null;
        $this->container['category'] = isset($data['category']) ? $data['category'] : null;
        $this->container['graphical_notation_defined'] = isset($data['graphical_notation_defined']) ? $data['graphical_notation_defined'] : false;
        $this->container['suspended'] = isset($data['suspended']) ? $data['suspended'] : false;
        $this->container['start_form_defined'] = isset($data['start_form_defined']) ? $data['start_form_defined'] : false;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets key
     *
     * @return string
     */
    public function getKey()
    {
        return $this->container['key'];
    }

    /**
     * Sets key
     *
     * @param string $key key
     *
     * @return $this
     */
    public function setKey($key)
    {
        $this->container['key'] = $key;

        return $this;
    }

    /**
     * Gets version
     *
     * @return int
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param int $version version
     *
     * @return $this
     */
    public function setVersion($version)
    {
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return $this
     */
    public function setTenantId($tenant_id)
    {
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets deployment_id
     *
     * @return string
     */
    public function getDeploymentId()
    {
        return $this->container['deployment_id'];
    }

    /**
     * Sets deployment_id
     *
     * @param string $deployment_id deployment_id
     *
     * @return $this
     */
    public function setDeploymentId($deployment_id)
    {
        $this->container['deployment_id'] = $deployment_id;

        return $this;
    }

    /**
     * Gets deployment_url
     *
     * @return string
     */
    public function getDeploymentUrl()
    {
        return $this->container['deployment_url'];
    }

    /**
     * Sets deployment_url
     *
     * @param string $deployment_url deployment_url
     *
     * @return $this
     */
    public function setDeploymentUrl($deployment_url)
    {
        $this->container['deployment_url'] = $deployment_url;

        return $this;
    }

    /**
     * Gets resource
     *
     * @return string
     */
    public function getResource()
    {
        return $this->container['resource'];
    }

    /**
     * Sets resource
     *
     * @param string $resource resource
     *
     * @return $this
     */
    public function setResource($resource)
    {
        $this->container['resource'] = $resource;

        return $this;
    }

    /**
     * Gets diagram_resource
     *
     * @return string
     */
    public function getDiagramResource()
    {
        return $this->container['diagram_resource'];
    }

    /**
     * Sets diagram_resource
     *
     * @param string $diagram_resource diagram_resource
     *
     * @return $this
     */
    public function setDiagramResource($diagram_resource)
    {
        $this->container['diagram_resource'] = $diagram_resource;

        return $this;
    }

    /**
     * Gets category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param string $category category
     *
     * @return $this
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets graphical_notation_defined
     *
     * @return bool
     */
    public function getGraphicalNotationDefined()
    {
        return $this->container['graphical_notation_defined'];
    }

    /**
     * Sets graphical_notation_defined
     *
     * @param bool $graphical_notation_defined graphical_notation_defined
     *
     * @return $this
     */
    public function setGraphicalNotationDefined($graphical_notation_defined)
    {
        $this->container['graphical_notation_defined'] = $graphical_notation_defined;

        return $this;
    }

    /**
     * Gets suspended
     *
     * @return bool
     */
    public function getSuspended()
    {
        return $this->container['suspended'];
    }

    /**
     * Sets suspended
     *
     * @param bool $suspended suspended
     *
     * @return $this
     */
    public function setSuspended($suspended)
    {
        $this->container['suspended'] = $suspended;

        return $this;
    }

    /**
     * Gets start_form_defined
     *
     * @return bool
     */
    public function getStartFormDefined()
    {
        return $this->container['start_form_defined'];
    }

    /**
     * Sets start_form_defined
     *
     * @param bool $start_form_defined start_form_defined
     *
     * @return $this
     */
    public function setStartFormDefined($start_form_defined)
    {
        $this->container['start_form_defined'] = $start_form_defined;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param  integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param  integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param  integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

