<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createGroup
     *
     * Create a group.
     *
     */
    public function testCreateGroup()
    {
    }

    /**
     * Test case for createMembership
     *
     * Add a member to a group.
     *
     */
    public function testCreateMembership()
    {
    }

    /**
     * Test case for deleteGroup
     *
     * Delete a group.
     *
     */
    public function testDeleteGroup()
    {
    }

    /**
     * Test case for deleteMembership
     *
     * Delete a member from a group.
     *
     */
    public function testDeleteMembership()
    {
    }

    /**
     * Test case for getGroup
     *
     * Get a single group.
     *
     */
    public function testGetGroup()
    {
    }

    /**
     * Test case for getGroups
     *
     * Get a list of groups.
     *
     */
    public function testGetGroups()
    {
    }

    /**
     * Test case for updateGroup
     *
     * Update a group.
     *
     */
    public function testUpdateGroup()
    {
    }
}
