<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sWIm Activiti REST API
 *
 * here be dragons
 *
 * OpenAPI spec version: v0.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createUser
     *
     * Create a user.
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for createUserInfo
     *
     * Create a new user�s info entry.
     *
     */
    public function testCreateUserInfo()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete a user.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for deleteUserInfo
     *
     * Delete a user�s info.
     *
     */
    public function testDeleteUserInfo()
    {
    }

    /**
     * Test case for getUser
     *
     * Get a single user.
     *
     */
    public function testGetUser()
    {
    }

    /**
     * Test case for getUserInfo
     *
     * Get a user�s info.
     *
     */
    public function testGetUserInfo()
    {
    }

    /**
     * Test case for getUserPicture
     *
     * Get a user�s picture.
     *
     */
    public function testGetUserPicture()
    {
    }

    /**
     * Test case for getUsers
     *
     * Get a list of users.
     *
     */
    public function testGetUsers()
    {
    }

    /**
     * Test case for listUsersInfo
     *
     * List a user�s info.
     *
     */
    public function testListUsersInfo()
    {
    }

    /**
     * Test case for updateUser
     *
     * Update a user.
     *
     */
    public function testUpdateUser()
    {
    }

    /**
     * Test case for updateUserInfo
     *
     * Update a user�s info.
     *
     */
    public function testUpdateUserInfo()
    {
    }

    /**
     * Test case for updateUserPicture
     *
     * Updating a user�s picture.
     *
     */
    public function testUpdateUserPicture()
    {
    }
}
